#!/bin/bash
export PATH="/usr/bin:/usr/local/bin:$PATH"
export GEM_HOME="/Users/wayneyu/.gem/ruby/2.6.0"
export GEM_PATH="/Users/wayneyu/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0"
cd "/Users/wayneyu/Documents/Development/Git/yky/triftly-app/ios" && bundle exec pod "$@"
